/**
 * PDF Labels & Text Constants
 *
 * SINGLE SOURCE OF TRUTH for all text displayed in the PDF export.
 * This ensures PDF/UI parity and prevents text drift.
 *
 * IMPORTANT CONSTRAINTS:
 * - Do NOT change any wording without stakeholder approval
 * - All text must match the UI exactly where applicable
 * - Disclaimer text is legally sensitive - never modify
 */

/**
 * Main PDF title displayed in header.
 */
export const PDF_TITLE = "EPR Fee Estimator";

/**
 * Logo alt text for accessibility.
 */
export const PDF_LOGO_ALT = "Portco Packaging";

/**
 * Metadata field labels (left column).
 */
export const PDF_META_LABELS = {
  state: "State:",
  program: "Program:",
  material: "Material:",
  weight: "Weight:",
  generated: "Generated:",
} as const;

/**
 * Fee summary section labels.
 * IMPORTANT: Must match UI verbatim (see ColoradoPhase2Breakdown.tsx)
 */
export const PDF_FEE_SUMMARY = {
  label: "Estimated 2026 Program Fee",
  subtitle: "JBC-Approved Medium Scenario",
} as const;

/**
 * Section titles (uppercase headers for each section).
 */
export const PDF_SECTION_TITLES = {
  timeline: "Fee Adjustment Timeline",
  breakdown: "Fee Breakdown",
  explanation: "Explanation of Fee",
  authority: "Authority & Basis",
} as const;

/**
 * Timeline-specific labels.
 */
export const PDF_TIMELINE = {
  startLabel: "Base Dues",
  finalLabel: "Final",
  caption: "Fee adjustment timeline — visual representation of applied deltas.",
} as const;

/**
 * Footer text template.
 * Use by replacing {date} with actual date string.
 */
export const PDF_FOOTER_TEMPLATE = "Generated by Portco Packaging EPR Fee Estimator · {date}";

/**
 * Build footer text with dynamic date.
 */
export function buildPDFFooterText(dateGenerated: string): string {
  return PDF_FOOTER_TEMPLATE.replace("{date}", dateGenerated);
}

/**
 * The exact disclaimer text required in all PDFs.
 * DO NOT MODIFY THIS TEXT - it is legally reviewed.
 *
 * NOTE: This is also exported from exportResultsToPDF.ts for backward
 * compatibility. Both exports reference the same constant.
 */
export const PDF_DISCLAIMER_TEXT = `Disclaimer
This packaging EPR fee estimator provides estimates for general informational purposes only and is not an official fee calculation. This tool does not constitute legal or compliance advice. Material categories and fee rates are subject to change.

Producers must consult with compliance professionals, the state agency, and/or the applicable producer responsibility organization to confirm their compliance obligation and total fees.`;
